[tool.poetry]
name = "modbot"
version = "0.1.0"
description = "CLI to add and remove dotfiles linked with Dotbot"
authors = ["Kevin Lane <lane.kevin.a@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/klane/modbot"

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
dotbot = "^1.14"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
pytest-cov = "^2.6"
pytest-lazy-fixture = "^0.5.2"
pytest-mock = "^1.10"
pytest-sugar = "^0.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
